FROM ubuntu:23.10

LABEL authors="Barrypp.zzx"
LABEL description="for wsl"

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 iptables lsof curl wget nano socat locales \
 iputils-ping mtr-tiny iproute2 httping \
 iperf iperf3 tcpdump iptraf iftop \
 g++ gdb make ninja-build rsync \
 xz-utils zip \
 usbutils \
 && apt-get autoclean && rm -rf /var/lib/apt/lists/*

WORKDIR /root