FROM ubuntu:23.04

LABEL authors="Barrypp.zzx"
LABEL description="for wsl"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 nano socat xz-utils iptables \
 iperf iperf3 iputils-ping traceroute mtr-tiny iproute2 \
 usbutils curl lsof tcpdump tcptrack iftop \
 g++ gdb make ninja-build rsync zip \
 && apt-get autoclean && rm -rf /var/lib/apt/lists/*

WORKDIR /root